version: "3"
services:
  hamlet_listener:
    image: index.docker.io/framaxwlad/talking_container:latest
    container_name: hamlet_listener
    command: -t "server"

  hamlet_reciter:
    image: index.docker.io/framaxwlad/talking_container:latest
    container_name: hamlet_reciter
    command: -t "client"
    depends_on:
      - hamlet_listener

networks:
  local_net:
    driver: bridge
