load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "talking_containers_lib",
    srcs = glob(["*.py"]),
    deps = ["//config_hangler"],
)
