name: CI / CD

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - uses: actions/checkout@v2

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Build Docker images
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" run -c opt //:talking_containers_image -- --norun

      - name: Deploy images to Dockerhub
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" run -c opt //:push_image
